server.port=8084
spring.application.name=returns-service

# Configuración de Base de Datos H2 en memoria para desarrollo rápido
spring.datasource.url=jdbc:h2:mem:returnsdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Consola H2 accesible en http://localhost:8084/h2-console
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true