server.port=8084
spring.application.name=returns-service

# Configuración de Base de Datos MySQL (MariaDB) local compartida
spring.datasource.url=jdbc:mysql://localhost:3306/bp_ventas
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Estrategia de JPA / Hibernate para autocreación de tablas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true